export const tweetActionTypes = ({
    FETCH_TWEET_START: "FETCH_TWEET_START",
    FETCH_MY_TWEET_START: "FETCH_MY_TWEET_START",
    FETCH_TWEET_SUCCESS: "FETCH_TWEET_SUCCESS",
    FETCH_TWEET_FAILURE: "FETCH_TWEET_FAILURE",
    CREATE_TWEET_START: "CREATE_TWEET_START",
    CREATE_TWEET_SUCCESS: "CREATE_TWEET_SUCCESS",
    CREATE_TWEET_FAILURE: "CREATE_TWEET_FAILURE",
    DELETE_TWEET_START: "DELETE_TWEET_START",
    DELETE_TWEET_SUCCESS: "DELETE_TWEET_SUCCESS",
    DELETE_TWEET_FAILURE: "DELETE_TWEET_FAILURE"
})