export const tweetActionTypes = ({
    FETCH_TWEET_START: "FETCH_TWEET_START",
    FETCH_MY_TWEET_START: "FETCH_MY_TWEET_START",
    FETCH_TWEET_SUCCESS: "FETCH_TWEET_SUCCESS",
    FETCH_TWEET_FAILURE: "FETCH_TWEET_FAILURE" 
})